export default {
	USER_LOAD : 'USER_LOAD',

	ALBUM_CHANGE : 'ALBUM_CHANGE',
	ALBUM_SHOWING : 'ALBUM_SHOWING',
	ALBUM_HIDDING : 'ALBUM_HIDDING',
	ALBUM_READY : 'ALBUM_READY',
	ALBUM_POPUP_SHOW : 'ALBUM_POPUP_SHOW',
	ALBUM_POPUP_HIDE : 'ALBUM_POPUP_HIDE',


	OPEN_POPUP : 'OPEN_POPUP',
}