export default {
	USER_LOAD : 'USER_LOAD',

	ALBUM_CHANGE : 'ALBUM_CHANGE',
	ALBUM_SHOWING : 'ALBUM_SHOWING',
	ALBUM_HIDDING : 'ALBUM_HIDDING',
	ALBUM_READY : 'ALBUM_READY',

	OPEN_POPUP : 'OPEN_POPUP',
}